"""First init.

Revision ID: 101f4a0f221c
Revises: None
Create Date: 2014-03-12 21:33:30.513347

"""

# revision identifiers, used by Alembic.
revision = '101f4a0f221c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    ### end Alembic commands ###
